### ISSUE TITLE
Can't seem to get fonts to load

### ISSUE THREAD

**Issue by mcarreon** [rohanray/next-fonts#16]
I'm trying to load in some Google Fonts in ttf format and they don't seem to want to load. I'm using next-fonts as well as SCSS for styling. The fonts are under in /static/fonts/ but I can't figure out what I'm doing wrong. Any help would be appreciated!

I'm loading the plugins like this:

```javascript
const withSass = require('@zeit/next-sass');
const withFonts = require('next-fonts');
const compose = require('next-compose');

module.exports = compose([[withFonts],[withSass]]);
```

And my SCSS imports are as such: 

```scss
@font-face {
  font-family: 'Ovo';
  font-weight: 400;
  src: url('/static/fonts/Ovo-Regular.ttf') format('ttf');
}

@font-face {
  font-family: 'Muli';
  font-weight: 400;
  src: url('/static/fonts/Muli.ttf') format('ttf');
}

@font-face {
  font-family: 'Muli';
  font-weight: 600;
  src: url('/static/fonts/Muli-SemiBold.ttf') format('ttf');
}
```
