### ISSUE TITLE
Suggestion to update documentation:

### ISSUE THREAD

**Issue by JBongars** [rohanray/next-fonts#5]
next-fonts does not work when you include font-face inside a global scss tag. I.e. 

Doing this will not work:-

``` scss
:global {
  @font-face {
    font-family: "SomeFont";
    src: url("./fonts/SomeFont-Bold.otf") format('opentype');
  
    src: url("./fonts/SomeFont-Bold.woff") format("woff"),
    url("./fonts/SomeFont-Bold.ttf") format("truetype"),
    url("./fonts/SomeFont-Bold.eot") format("eot"),
    url("./fonts/SomeFont-Bold.svg") format("svg");
    font-weight: normal;
    font-style: normal;
  }
}
```
Please add to documentation

Cheers
